version: '3'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    container_name: db
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: forbxpg/tasks_backend:latest
    env_file: .env
    container_name: backend
    volumes:
      - static_volume:/backend_static
  frontend:
    image: forbxpg/tasks_frontend
    env_file: .env
    container_name: frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: forbxpg/tasks_gateway
    env_file: .env
    container_name: gateway
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80