name: Main workflow
on:
  push:
    branches:
      - main

jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Print tree
        run: tree .